readme.md

The Fantom Windows Installer has been migrated to GitHub @ https://github.com/Fantom-Factory/fantomWindowsInstaller
Note I'm also consolidating a lot "Alien Factory" nomenclature to "[Fantom Factory](https://www.fantomfactory.com/)" - so if I may, I'd like to ask for the details on the new [Fantom download page](https://fantom.org/download) to be updated too.

Updated Fantom Windows Installer download link

---

src/web/fan/WebClient.fan

Instead of adding new methods for `patchX` I created public `writeX` methods for WebClient, and changed `postX` to route to those as a convenience.

web: add generic write(Str|Form|File) utils to WebClient

---

src/sys/js/fan/ObjUtil.js

It doesn't look like it's being used - a copy/paste error from ObjUtil.compare() perhaps?

Removed "op" parameter from fan.sys.ObjUtil.equals()

---

.github/workflows/publish.yaml
dockerfile
src/.dockerignore

This adds the following:
1. A Dockerfile that will build a Fantom docker image from the local repo
2. A GitHub action that will automatically run this dockerfile and publish it to the GitHub package repo. This will trigger on any push to `master`, including commits and tags. My experience is that a commit will tag the image with the branch name, whereas a tag will apply the tag name.
I'm sure the resulting image size could be whittled down quite a bit if desired.

GitHub Action Docker Builds

---

src/math/fan/BigInt.fan
src/math/java/BigInt.java
src/sys/fan/Int.fan

Split this into two commits:
1. A clean-up commit which has the following:
* Added documentation for all the existing `math::BigInt` methods (mostly a combination from Int and java's BigInteger + a bit of my own comments).
* `sys::Int.toRadix`'s example was inaccurate 🙂.  Fixed to be a better example.
* I noticed the files were using both using tabs and spaces together for indentation. 
I converted them all to be consistent.  I noticed the pod was mostly using tabs, so I made the few random spaces into tabs to keep it clean.  If you want the whole pod converted to spaces (which both I prefer as well as I notice most of Fantom is written in), I can amend this with that change.
* `math::BigInt.shiftr` was misspelled "shftr".
2. The primary commit which added a bunch of new methods to …

BigInt arithmetic

---

src/yaml/fan/YamlObj.fan
src/yaml/fan/YamlParser.fan
src/yaml/test/BasicYamlTest.fan

The `loc` field in each parsed `YamlObj` should now have a known value. Instead of being `FileLoc.unknown`, it should now track corresponding line and column numbers in the file/string it is parsing.

Add proper file loc tracking to YAML

---

.dockerignore
.github/workflows/publish.yaml
dockerfile
readme.md

This fixes the following issues with the Docker image generation:
1. Docker images were published only on commits to `master`, and not on git release tags. This PR ensures that images are automatically built on any `v*` git tag, applying the `vX.X.X` and `latest` docker tags. 
2. Docker images were built on Java 8. This bumps them to Java 17, and makes the version configurable using a Docker build arg.
3. The docker CI was using commit-hash dependencies. This changes them to the mainline versions.
It also fixes little inconsistencies and adds some documentation.

Docker CI fixes

---

src/compiler/fan/assembler/CodeAsm.fan

Unresolved `unknownVar` exprs would throw an `Err` with an unhelpful msg.
With this change, a more useful `CompilerErr` is reported, with a location, and with a lot more informative context in the msg.

compiler: Let unknownVar throw CompilerErr with more informative context

---

src/dom/es/DocPeer.js
src/dom/es/EventPeer.js
src/dom/es/WeakMapPeer.js
src/nodeJs/fan/ts/CompileTsPlugin.fan
src/nodeJs/fan/ts/TsDocWriter.fan

In full:
- Method names are no longer swizzled in declaration files
- The Func class declaration matches the implementation, with static methods
- Removed extra $ in ObjUtil declaration file & dom's WeakMap
- Added ES implementation of dom methods that were recently added in JS (elemFromPos, elemsFromPos, relatedTarget)

Updated TS decl writer & dom pod, mostly to align with the swizzle change

---

src/dom/java/EventPeer.java

Event.button() defines a return type of `Int?` requiring a Java `Long` primitive wrapper class.

Fix for EventPeer.button() returning the wrong type

---

src/sql/java/SqlUtil.java
src/sql/java/StatementPeer.java

This pull request improves support for Postgres in the sql pod.
- The Postgres `text[]` field type is now supported by the Fantom `Str[]` type. 
- The Postgres `@>` containment operator no longer generates an error when parsing SQL.
For example, if we have a table defined like this:
```
create table foo (
id text primary key,
bar text[] not null
);
create index foo_bar on foo using gin (bar);
```
Then the following test suite snippet demonstrates how these new features work:
```
insert := conn.sql(
"insert into foo (id, bar) values (@id, @bar)").prepare
insert.execute([
"id":"abc",
"bar":["x", "y", "z"]
])
filter := conn.sql(
"select * from foo where (foo.bar @> @bar::text[])").prepare
rows = filter.query(["bar":"{\"x\"}"])
verifyEq(rows.size, 1)
f = rows[0]
verifyEq(f->id, "abc") …
```

sql: add support for Postgres text[] and '@>' operator

---

src/sql/fan/SqlConn.fan
src/sql/fan/SqlConnPool.fan
src/sql/fan/Statement.fan
src/sql/java/SqlConnPoolPeer.java
src/sql/java/StatementPeer.java
src/sql/pod.fandoc
src/sql/test/SqlServiceTest.fan

This PR contains various improvements to the sql pod:
- Add `queryEachWhile()` to `Statement`
- Add `onOpen()` and `onClose()` to `SqlConnPool`
- Close all ResultSets properly
- Modify the test suite so that it works for both Postgres and MySQL
- Update the documentation

Various improvements to the sql pod

---

src/sql/java/SqlUtil.java

This is a fix for a bug in the sql pod, so that we now only write out the bytes in a MemBuf that are actually being used, instead of writing out the entire capacity of the MemBuf.

sql: fix so that writing a byte array only writes the bytes being used

---

src/sql/fan/Tokenizer.fan
src/sql/java/StatementPeer.java
src/sql/test/SqlServiceTest.fan
src/sql/test/TokenizerTest.fan

_**BREAKING CHANGE**_
This PR introduces a new escape syntax for the `@` character in prepared Statements, and causes a breaking change by deprecating an old undocumented syntax.  
When calling `Statement.prepare()`, the strings `\@` and `\\` in the Statement's SQL are now translated into `@` and `\` respectively.  
Examples:
In mysql, to refer to the [user variable](https://dev.mysql.com/doc/refman/8.4/en/user-variables.html) `@v1` in a prepared Statement:
select name, \@v1 from foo where id = @id;
In postgres, to use the [JSONB operator](https://www.postgresql.org/docs/9.5/functions-json.html) `@>` in a prepared Statement:
select * from foo where data \@> '{"x": 99}'::jsonb;
There is an old, undocumented syntax for referring to mysql user variables, using the escape sequence `@@v1`, for …

sql: BREAKING CHANGE -- create new escape syntax for the "@" character in prepared Statements.

---

etc/sql/config.props
src/doc/docIntro/doc/ChangeLog.fandoc
src/sql/java/StatementPeer.java
src/sql/pod.fandoc

Miscellaneous documentation updates, plus a minor code change:
- Update pod.fandoc
- Add commented out setting for `deprecatedEscape` to `etc/sql/config.props`
- Update package name to latest mysql driver in `etc/sql/config.props`
- Update docIntro/Changelog
- Clean up Statement Peer

sql: update documentation

---

src/doc/docIntro/doc/ChangeLog.fandoc
src/sql/fan/Statement.fan
src/sql/java/StatementPeer.java
src/sql/test/SqlServiceTest.fan

Add a `Statement.executeBatch` method, which will execute a batch of commands on a prepared Statement.

sql: add Statement.executeBatch method

---

etc/sql/config.props
src/sql/pod.fandoc
src/sql/test/SqlTest.fan

- Rename `SqlServiceTest` to `SqlTest`, and modify it so that it runs automatically against both mysql and postgres.
- Remove disused test settings from `etc/sql/config.props`.
- Update the pod.fandoc to reflect this change, and move the relevant section to the bottom of the doc.

sql: rename SqlTest, and modify it so that it runs automatically against both mysql and postgres.

---

src/util/fan/JsonOutStream.fan
src/util/test/JsonTest.fan

For JSON strings, the characters that are below `0x20`, but are not one of `\b`, `\f`, `\n`, `\r` or `\t`, are not being escaped into `\uXXXX` format by JsonOutStream.  For example, `0x00` is not being properly escaped into `\u0000`.  This PR fixes that bug.
JsonInStream's current behaviour is that it can properly decode escaped sequences like `\u0000`, but it _also_ will decode raw unescaped bytes like `0x00`.  I think this may not really allowed by the JSON spec, but this PR does not have a fix for that behaviour.

util: fix JsonOutStream so characters below 0x20 are encoded properly.

---

src/sql/java/SqlUtil.java
src/sql/test/SqlTest.fan

Add read/write support for Postgres's 4-byte `int[]` array field, and 8-byte `bigint[]` array field.

sql: improve support for Postgres array fields

---

src/sql/java/SqlUtil.java
src/sql/test/SqlTest.fan

Add support for more postgres array types:  `bool[]`, `real[]`, `double precision[]`, and `timestamptz[]`.

sql:  Add support for more postgres array types

---

src/sys/java/fan/sys/List.java

ListItr was incorrectly incrementing the iterator before retrieving the value when the rest of the methods expect that cursor always points to the next index (see nextIndex method).
On top of that next() was also throwing NoSuchElementException when hasNext was still true due to the same issue.
With this fix you can now use foreach loop in Java without hitting a NoSuchElementException

Fix iterator skipping first element & returning NoSuchElementException early
